### ISSUE TITLE
status/tracking 

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#14]
## Value Proposition

As a User
I want to see the tricks I'm learning and the tricks I've already mastered
so that I can track my progress
​

## Description

<img width="1080" alt="8  user story" src="https://user-images.githubusercontent.com/117775795/214854161-3d507d82-3c79-447a-9bb3-ed7af5f5d5f5.png">

## Acceptance Criteria

- [ ] the status of the trick (learning/mastered) is displayed in the repertoire page
- [ ] the status of the trick (learning/mastered) is displayed in the repertoire page
- [ ] 2 radio buttons are displayed in the edit form
      ​

## Tasks

- [ ] Find a way to display the status of the trick
- [ ] edit the form so that you can change the status 

      ​

## Complexity

S

**Comment by SaschaRadojkovic** [comment]
you have two times the same acceptance criteria  the status of the trick (learning/mastered) is displayed in the repertoire page. if i understand it right should one of them be the details page !?

**Comment by TariqAlQadi** [comment]
Thanks Sascha
I will update it!
