### ISSUE TITLE
profil page

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#15]
## Value Proposition

As a User
I want to have a profil page
so i can see/ show my stats
​

## Description

<img width="985" alt="9  user story" src="https://user-images.githubusercontent.com/117775795/214859270-2c3323a4-a9cc-4396-9c8c-ba5c04eb3542.png">

​
## Acceptance Criteria

- [ ] a navlink to the profil page is displayed on every page
- [ ] on the profil page there is a placeholder image displayed
- [ ] on the profil page there is the user information displayed
- [ ] on the profil page there are the stats of the user displayed
- [ ] on the profil page there is an edit button displayed wich opens an edit form to edit the user information except the image & stats
      ​
## Tasks

- [ ] create a profil page  & routing
- [ ] adapt the navigation accordingly
- [ ] create an placeholder image or avatar 
- [ ] create profil edit form and edit button 
- [ ] create add function for stats and lvl/xp
- [ ] find a solution to display it 
      ​

## Complexity

L

**Comment by anotherMichaelMaier** [comment]
looks like a well structured and detailed US to me. Keep up the good work!
