### ISSUE TITLE
first styling

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#16]
## Value Proposition

As a User
I want to have some simple stylings 
so that the app is more comfortable to use 
​

## Description

First simple Styling for the components 
​
## Acceptance Criteria

- [ ] The category lists are always displayed
- [ ] styled button component is the only button component
      ​

## Tasks

- [ ] create styling for the components
- [ ] create styled button with variants
​

## Complexity

S

**Comment by anotherMichaelMaier** [comment]
lgtm. :)
