### ISSUE TITLE
Detailspage

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#2]
### Value Proposition

As a User,

I want to to see more information about the tutorials,

so that I can decide wich one to learn.

### Description

<img width="350" alt="Screenshot 2023-01-19 at 15 17 52" src="https://user-images.githubusercontent.com/117775795/213465999-e1e4d46d-f02a-4422-b0a9-563637c90882.png">

### Acceptance Criteria

- [ ] If a card is clicked, the user will see a details page
- [ ] The tutorial details page displays the name of the tutorial
- [ ] The tutorial details page displays the video of the tutorial
- [ ] The tutorial details page displays the creator of the tutorial
- [ ] The tutorial details page displays the description of the tutorial
- [ ] User can return to the tutorial list by clicking the back link

### Tasks

 - [ ] add a link to each list item, that links to the details page
 - [ ] add dynamic routing and create a details page that displays all Acceptance Criteria
      ​

## Complexity

M
