### ISSUE TITLE
shop page

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#21]
## Value Proposition

As a User 
I want to have a shop page
so that I know where to buy props 
​

## Description

<img width="701" alt="11  user story" src="https://user-images.githubusercontent.com/117775795/215335079-0e3d7d49-e65c-4042-b33a-7d3e06b41b64.png">

​
## Acceptance Criteria

- [ ] a navigation link to the shop page is displayed on every page
- [ ] a list of links to online shops is displayed
      ​

## Tasks

- [ ] add a shop page with different links
- [ ] add a navigation link
      ​

## Complexity

S

**Comment by JohannesMisch** [comment]
LGTM.
