### ISSUE TITLE
Refactoring pages

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#23]
## Value Proposition

As a User
I want to have a logical order for the application
so that I don't have page and link for every new feature
​

## Description

<img width="805" alt="12  user story" src="https://user-images.githubusercontent.com/117775795/215468592-042ed4a0-8531-459e-b157-3726f31377a1.png">

## Acceptance Criteria

- [ ] no "search" or "bookmark" page or nav link is displayed
- [ ] a new "feed" page is displayed with all functions of the "categories" and "search" page 
- [ ] the "profil" page displays 2 sections with tabs (1 for the stats and one for bookmarked tutorials)
- [ ] the "liked" list is disyplayed in the "profil" page
      ​

## Tasks

- [ ] remove "search" & "bookmark" page
- [ ] integrate the logic of the 2 pages in new "feed" & "profil" page
- [ ] adapt the profil page so that it has 2 sections (they toggle to active state and display according content)

      ​

## Complexity

M

**Comment by marcterre** [comment]
Hey Tariq, i would define "no nav link is displayed" more, like "no link to this pages in the navigation is displayed anymore". Also i think you mention the "liked"-list two times: "...(1 for the stats and one for bookmarked tutorials)" and the "liked" list is disyplayed in the "profil" page" - just delete the last one.

**Comment by TariqAlQadi** [comment]
Thanks! :)
