### ISSUE TITLE
upload page

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#24]
## Value Proposition

As a User 
I want to have an upload function
so that I am able to upload my own content
​

## Description

![13  user story](https://user-images.githubusercontent.com/117775795/215719237-7413d3a0-41f1-414e-8d13-558c27a9a618.png)

## Acceptance Criteria

- [ ] an upload page is displayed
- [ ] a new upload nav link is displayed
- [ ] the submit of the form renders a new entry in the feed
- [ ] the uplaods are displayed in the profil page in the another tab
- [ ] when submit is clicked a success message appears
      ​

## Tasks

- [ ] create an upload page
- [ ] create an upload form
- [ ] create a way to display the uploads on the profil page in a new section
- [ ] find a solution with cloudinary to make the data persistent 
- [ ] create a message toast for successful upload
      ​

## Complexity

L

**Comment by marcterre** [comment]
Hey again, i dont know how you want to display your upload on the profil page. "In the another tab" is not enough. Maybe use a wireframe. Same with your feed. 
What happens when i click the add button? Do i stay on this page or does it lead somewhere? If i stay on this page how am i sure i added something new? Integrate a submit message. 🙂

**Comment by TariqAlQadi** [comment]
Thanks for your recommendations 👍

**Comment by RobinWitt** [comment]
looks good to me
