### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#26]
## Value Proposition

As a User
I want to have a nice landing page 
so that I feel welcome when opening the app
​

## Description

<img width="573" alt="14  user story" src="https://user-images.githubusercontent.com/117775795/215774365-19bb83f1-3fa6-498e-8548-0e1e5a9cde32.png">

## Acceptance Criteria

- [ ] on the landing page the title of the website is displayed
- [ ] on the landing page a little description of the webapp is displayed
- [ ] a fake Login is displayed
- [ ] when "login" in and the data is correct the user gets directed to the tutorials page
      ​

## Tasks

- [ ] Create a title and discription for the webapp
- [ ] create a fake login form with
- [ ] create a email input
- [ ] create a password input 
- [ ] create a submit button
      ​

## Complexity

M

**Comment by AstridOttmann** [comment]
Looks good! 
Two things I want to note: 
As the fake-login seems to be the main feature of the userstory I would suggest to make this the content of the Value Proposition, i. e. 
as a user I want to have a login,  so that I can create a personal account. 
Maybe you can add the link to the tutorial page in the tasks.
