### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#27]
## Value Proposition

As a User get different achievements
so that I am motivated to train more
​

## Description

<img width="488" alt="15  user story" src="https://user-images.githubusercontent.com/117775795/215776556-54c56336-a242-46d5-89d6-80b3417ac2c7.png">

## Acceptance Criteria

- [ ] different achievements are added ( for lvl, first tutorial of every difficulty, etc)
- [ ] they're display in the stats section of the profile page
      ​

## Tasks

- [ ] create different achievement with according logic 
- [ ] find a way to display them nicely 
      ​

## Complexity

M

**Comment by niklasrammelkamp** [comment]
Hi Tariq, I like the challenge but could you please explain in more detail what achievements you wanna display? If I would have to code this I wouldn't know what you wanna see. And the Tasks are a bit very crude and leave much space for interpretation.

**Comment by TariqAlQadi** [comment]
Ill change that
