### ISSUE TITLE
Backend/MongoDB

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#32]
## Value Proposition

As a Developer 
I want to provide a backend with MongoDB
so that the users data is persistent
​

## Description

Adding a database with MongoDB to make the data persistent.
The database includes the array of all tutorials and an user array with user information.
Add API routes
​

## Acceptance Criteria

- [ ] All the informations are displayed like before
- [ ] The (changed) data is persistent now 
- [ ] The data is different from user to user 
      ​

## Tasks

- [ ] Add an array of tutorials to the mongoDB database
- [ ] Add an array of users to the mongoDB database
- [ ] Create the according API routes
      ​

## Complexity

L

**Comment by marcterre** [comment]
nothing special to display here, nice one
