### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#37]
## Value Proposition

**As a** User
**I want to** be able to register myself
**so that** I can create my own account
​

## Description

​

## Acceptance Criteria

- [ ] a registration link is displayed on the landing page 
- [ ] when clicked it opens a registration form with 3 inputs (email & 2x password) & a sign-up button
- [ ] when clicked and given passwords are correct a new user object gets created (with default settings) and you get logged-in
      ​

## Tasks

- [ ] add registration form with an email & 2 password inputs & a sign-up button
- [ ] add api route for POSTING user object 
- [ ] add logic for thats checks if the email is already taken & if the passwords are identical​

## Complexity

M

**Comment by niklasrammelkamp** [comment]
lgtm
