### ISSUE TITLE
Overview with categories

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#4]
## Value Proposition

As a User
I want to have a categorization for my homepage
so i can easily find the tutorial I want to learn
​

## Description

<img width="834" alt="4  userstory" src="https://user-images.githubusercontent.com/117775795/213537600-3c95c666-7254-46c2-95bd-89874b3e9084.png">

## Acceptance Criteria

- [ ] An Overviewpage with categories is displayed 
- [ ] Different Categorypages can be displayed
- [ ] A link in the Categorypages is displayed that leads back to the Overviewpage
      ​

## Tasks

- [ ] Refactor the Homepage to the Overviewpage 
- [ ] Add different Categorypages 
- [ ] Add links to navigate between pages
      ​

## Complexity

M

**Comment by RobinWitt** [comment]
Hi Tariq, 
the scope and complexity of this user story look good to me!
But it is not clear how you want to implement the categorization, for example, if the category names are hard coded or generated and what tasks the developer should follow so that only the right tutorials are displayed in the respective categories.

I hope this feedback is helpful to you.

**Comment by TariqAlQadi** [comment]
Hi Robin, 
Thank you for reviewing and the question seems justified to me!
Your should know that the categorization should be easy, because I can fetch the category too!

**Comment by RobinWitt** [comment]
That makes it a lot easier, indeed. I think it would be perfect to describe that in the 'criteria' and 'tasks' above, to prevent other people from asking the same question as I did.

**Comment by RobinWitt** [comment]
Now that you made the changes I think this user story is fine, in my opinion. 
You get my approval :D
