### ISSUE TITLE
Notes input

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#5]
## Value Proposition

As a User
I want to be able to make notes on the Detailspage 
so that I can have a short summary of the tutorial
​

## Description

​
<img width="697" alt="Screenshot 2023-01-20 at 10 59 17" src="https://user-images.githubusercontent.com/117775795/213667908-26db3e8b-2cc5-40f5-a49a-4fbb0cb8d52c.png">

## Acceptance Criteria

- [ ] A note is displayed on every Detailspage
- [ ] An "Edit" button (type submit) is displayed in every note 
      ​

## Tasks

- [ ] Add a textinput for notes 
- [ ] Add a form & label for the input
- [ ] Add a submit button 

## Complexity

S

**Comment by ThomasF85** [comment]
Very nice and small user story!

I am missing one thing here. If I understand it right you want the note to be added to the tutorial, so that a user can see the note the next time they open the detailspage.
If that's correct please add another acceptance criteria which explains what effect the edit button click has.

**Comment by TariqAlQadi** [comment]
Thanks for reviewing!
The intention is to have the notes form ready and make the data persistent later on.
I should have been more clear about that!

**Comment by RobinWitt** [comment]
Looks like a nice feature to me!
