### ISSUE TITLE
Date & Difficulty 

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#6]
## Value Proposition

As a User
I want to see when the content got uploaded and the difficulty of the tutorial
so that I have all the information I need before watching it 
​

## Description

<img width="540" alt="Screenshot 2023-01-20 at 11 40 09" src="https://user-images.githubusercontent.com/117775795/213675986-0bbe71d6-cbc1-4e30-911e-a4c2398f3f51.png">

## Acceptance Criteria

- [ ] The difficulty is displayed on every Detailspage
- [ ] The date of the upload is displayed on every Detailspage
      ​

## Tasks

- [ ] Add the date information 
- [ ] Add the difficulty as a number

​
## Complexity

S

**Comment by doemser** [comment]
I'm not sure why the upload date is so relevant to the purpose, but the user-story looks good, good scope, some improvements I see: 

- Add to your AC the formatting of the date, this is quite relevant.
- Complexity might be XS
- Your wireframe has super many elements that lead nowhere, e.g. the navigation in the upper right corner. In each iteration, try to program and display only what will really be there and remove everything that does not exist at that time.

**Comment by TariqAlQadi** [comment]
Thank you for reviewing!
The date is not indispensable, but can be relevant, because today content develops fast and maybe the user wants to see the newest content! 
But I will think about the date and change the user story accordingly!

**Comment by doemser** [comment]
You can leave the date well and good in the details, I would just take the correct formatting of it into the AC.
