### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by TariqAlQadi** [TariqAlQadi/capstone-project#7]
## Value Proposition

As a User
I want to be able to search for content 
so that I can find it in an instant
​

## Description

<img width="461" alt="7  user story" src="https://user-images.githubusercontent.com/117775795/213715927-2b7f78b1-e6e8-49ae-9e75-f4f500e3e403.png">

​
## Acceptance Criteria

- [ ] A navigation in the navigation bar is displayed
- [ ] An search page with search bar is displayed
- [ ] The search bar filters the content by the given input and displays it 
      ​

## Tasks

- [ ] Add a search page 
- [ ] Add a navigation link to the search page 
- [ ] Add displayed list with filter logic
      ​

## Complexity

L

**Comment by AGeck113** [comment]
Hey Tariq, could you write a little bit more at  "Add displayed list with filter logic"
- Add filter function
- display filtered list 
(- As Card Component?)

**Comment by TariqAlQadi** [comment]
Hey Andreas, thank you for your comment!
I'll change the issue like you recommended :)

**Comment by ThomasF85** [comment]
My comments:
- I think you have a typo / wrong word in this AC: A navigation in the navigation bar is displayed
- Please also describe whether the search page is initially empty or filled with all cards before the user starts typing

**Comment by TariqAlQadi** [comment]
Thank you! You are so right and I'll change it!
